sudo: false
language: java
jdk: openjdk12

branches:
  except:
    /^pre/


before_deploy:
  - "[ -f .version ] && source .version || VERSION=x.x"
  - "./gradlew clean"
  - "./gradlew -PVERSION=${VERSION} -PTRAVIS_BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} jar"

deploy:
  - provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    prerelease: true
    name: "pre-v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    tag_name: "pre-v${VERSION}.${TRAVIS_BUILD_NUMBER}"
    on:
      tags: false
      branch: master
  - provider: releases
    api_key: $GIT_AUTH
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    on:
      tags: true
